on:
  push:
    branches:
      - master

jobs:
  ApkSizeTracker:
    runs-on: ubuntu-latest
    name: Apk size tracker
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: 16

      - name: Upload action step
        id: apkSize
        uses: zsfVishnu/apk-metric-upload@t1
        with:
          flavor: 'debug'
          is-react-native: true
          
          
          
          
          
          
          
          
      



